name = "LaTeXt"
uuid = "86a489f9-b43a-4f33-a11d-db7a5aa6bbb6"
authors = ["Jean-Francois Baffier"]
version = "0.1.0"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
