name = "LaTeXUniCode"
uuid = "86a489f9-b43a-4f33-a11d-db7a5aa6bbb6"
authors = ["Jean-Francois Baffier"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
